/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atena;

import SecuGen.FDxSDKPro.jni.JSGFPLib;
import SecuGen.FDxSDKPro.jni.SGDeviceInfoParam;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.GroupLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author svt
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private ImageIcon icon;
    Image iconImg;
    private ImageIcon iconControl;
    private boolean validacion = false;
    private JSGFPLib fplib;
    private SGDeviceInfoParam deviceInfo;

    public Inicio() {
        initComponents();
        icon = new ImageIcon("images\\biometric2.png");
        iconControl = new ImageIcon("images\\hamsterPlus.png");
        iconImg = icon.getImage();
        //jLabelImage.setIcon("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel(){
            public void paintComponent(Graphics g) {
                g.drawImage(iconImg, 0, 0, null);
                super.paintComponent(g);
            }};
            jSeparator1 = new javax.swing.JSeparator();
            menuControl = new javax.swing.JPanel();
            jLabel4 = new javax.swing.JLabel();
            jLabelImage2 = new javax.swing.JLabel(){
                public void paintComponent(Graphics g) {
                    g.drawImage(iconControl.getImage(), 0, 0, null);
                    super.paintComponent(g);
                }};
                jSeparator3 = new javax.swing.JSeparator();
                panelPrincipal = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                lblMensajes = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Sistema Atena - Control de ingreso");
                setBackground(new java.awt.Color(0, 153, 255));
                setBounds(new java.awt.Rectangle(0, 0, 0, 0));
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setForeground(new java.awt.Color(0, 153, 255));
                setName("principal"); // NOI18N
                setUndecorated(true);
                setResizable(false);
                setType(java.awt.Window.Type.POPUP);

                jPanel1.setBackground(new java.awt.Color(192, 222, 237));

                menuRegistro.setBackground(new java.awt.Color(192, 222, 237));
                menuRegistro.setForeground(new java.awt.Color(255, 255, 255));
                menuRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                menuRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        menuRegistroMouseClicked(evt);
                    }
                });

                jLabel1.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
                jLabel1.setText("Registro biométrico");

                jSeparator1.setBackground(new java.awt.Color(51, 153, 255));
                jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                javax.swing.GroupLayout menuRegistroLayout = new javax.swing.GroupLayout(menuRegistro);
                menuRegistro.setLayout(menuRegistroLayout);
                menuRegistroLayout.setHorizontalGroup(
                    menuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegistroLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(menuRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                );
                menuRegistroLayout.setVerticalGroup(
                    menuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                menuControl.setBackground(new java.awt.Color(192, 222, 237));
                menuControl.setForeground(new java.awt.Color(255, 255, 255));
                menuControl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                menuControl.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        menuControlMouseClicked(evt);
                    }
                });

                jLabel4.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
                jLabel4.setText("Control de acceso");

                jSeparator3.setBackground(new java.awt.Color(51, 153, 255));
                jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                javax.swing.GroupLayout menuControlLayout = new javax.swing.GroupLayout(menuControl);
                menuControl.setLayout(menuControlLayout);
                menuControlLayout.setHorizontalGroup(
                    menuControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuControlLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(menuControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                );
                menuControlLayout.setVerticalGroup(
                    menuControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menuRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 525, Short.MAX_VALUE))
                );

                panelPrincipal.setBackground(java.awt.Color.darkGray);
                panelPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
                panelPrincipal.setLayout(panelPrincipalLayout);
                panelPrincipalLayout.setHorizontalGroup(
                    panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 1132, Short.MAX_VALUE)
                );
                panelPrincipalLayout.setVerticalGroup(
                    panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
                );

                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Cerrar");
                jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel2MouseClicked(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMensajes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void menuRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistroMouseClicked
        // TODO add your handling code here:
        //System.out.println("clicked");
        displayRegistro();
        
    }//GEN-LAST:event_menuRegistroMouseClicked

    private void menuControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuControlMouseClicked
        // TODO add your handling code here:
        displayControl();
    }//GEN-LAST:event_menuControlMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelImage1;
    private javax.swing.JLabel jLabelImage2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblMensajes;
    private javax.swing.JPanel menuControl;
    private javax.swing.JPanel menuRegistro;
    private javax.swing.JPanel menuRegistro1;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    void setMensaje(String mensaje) {
        this.lblMensajes.setText(mensaje);
    }

    void setValidacion(boolean lectorInit) {
        this.validacion = lectorInit;
    }

    void setFplib(JSGFPLib fplib) {
        this.fplib=fplib;
    }

    void setDeviveInfo(SGDeviceInfoParam deviceInfo) {
        this.deviceInfo=deviceInfo;
    }

    public void displayRegistro() {
        if (validacion) {
            RegistroBio reg = new RegistroBio();
            panelPrincipal.removeAll();
            panelPrincipal.add(reg);
            validate();
            reg.setFplib(fplib);
            reg.setDeviveInfo(deviceInfo);
            reg.setPadre(this);
            reg.validate();
            reg.setLocation(0, 0);
            reg.setSize(700, 700);
            reg.setVisible(true);
            panelPrincipal.repaint();
        }
    }
     public void displayControl() {
        if (validacion) {
            ControlAcceso control = new ControlAcceso();
            panelPrincipal.removeAll();
            panelPrincipal.add(control);
            validate();
            control.setFplib(fplib);
            control.setDeviveInfo(deviceInfo);
            control.setPadre(this);
            control.validate();
            control.setLocation(0, 0);
            control.setSize(700, 700);
            control.setVisible(true);
            panelPrincipal.repaint();
        }
    }
}
